# Header

menu:
  ä¸»é¡µ: /
  æ–‡ç« : /archives/

# SubNav
subnav:
  github: "https://github.com/liwenliang"
  weibo: "https://weibo.com/u/2413488337"
#  rss: "/atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:792831375@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: more
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'

fancybox: true
# æ•°å­¦å…¬å¼
mathjax: false
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 0
# æ‰“èµwording
reward_wording: 'è°¢è°¢ä½ è¯·æˆ‘åƒç³–æœ'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay: /assets/img/alipay.jpg
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: /assets/img/wxpay.jpg

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 2
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: false
favicon: /assets/img/favicon.png

mobile:
  social: true

#ä½ çš„å¤´åƒurl
avatar: /assets/img/head.jpeg

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
changyan_appid: false
changyan_conf: false

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: ''          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæˆ‘'

friends:
  Node åœ°ä¸‹é“: http://nodejs.club/
  Linuxå‘½ä»¤å¤§å…¨: http://man.linuxde.net/
  ç™¾åº¦ FEX: http://fex.baidu.com/
  é½èˆå›¢: http://www.75team.com/
  å‡¹å‡¸å®éªŒå®¤: http://aotu.io/notes/
  è…¾è®¯ AlloyTeam: http://www.alloyteam.com/
  æ·˜å®å‰ç«¯å›¢é˜Ÿ: http://taobaofed.org/
  å›¾ç‰‡åˆ†äº«ç¤¾ç¾¤: https://unsplash.com/
  JavaScriptæ ‡å‡†å‚è€ƒ: http://javascript.ruanyifeng.com/
  ECMAScript 6 å…¥é—¨: http://es6.ruanyifeng.com/
  js1k: https://js1k.com/
  ğŸŒç«æ˜ŸèŠå¤©å®¤: http://chat.houjiyi.com

aboutme: kiviï¼Œä¸æ–­è¿›æ­¥çš„é’å¹´
